from __future__ import annotations

import unittest
from datetime import datetime, timezone

from app.services.notifications.alert_formatter import (
    format_alert_email_body,
    format_alert_email_subject,
    format_alert_line,
)
from app.services.notifications.email_notifier import EmailConfig, build_email_message


def make_alert() -> dict:
    return {
        "alert_id": 7,
        "artist_name": "Metallica",
        "event_date": datetime(2026, 6, 1, 18, 0, tzinfo=timezone.utc),
        "venue_name": "PGE Narodowy",
        "city": "Warsaw",
        "country_code": "PL",
        "match_type": "city_and_venue",
        "event_url": "https://example.com/event",
    }


class AlertFormatterTest(unittest.TestCase):
    def test_format_alert_line_contains_core_event_details(self) -> None:
        line = format_alert_line(make_alert())

        self.assertIn("[#7] Metallica", line)
        self.assertIn("PGE Narodowy, Warsaw, PL", line)
        self.assertIn("match=city_and_venue", line)
        self.assertIn("https://example.com/event", line)

    def test_format_email_subject_handles_single_and_multiple_alerts(self) -> None:
        alert = make_alert()

        self.assertEqual(format_alert_email_subject([alert]), "1 new concert alert")
        self.assertEqual(
            format_alert_email_subject([alert, alert]),
            "2 new concert alerts",
        )

    def test_format_email_body_contains_all_alerts(self) -> None:
        body = format_alert_email_body([make_alert()])

        self.assertIn("New concert alerts:", body)
        self.assertIn("Metallica", body)
        self.assertIn("Generated by The Live Music Project.", body)


class EmailNotifierTest(unittest.TestCase):
    def test_build_email_message_uses_config_headers(self) -> None:
        config = EmailConfig(
            smtp_host="smtp.example.com",
            smtp_port=587,
            smtp_username=None,
            smtp_password=None,
            sender="alerts@example.com",
            recipients=["one@example.com", "two@example.com"],
        )

        message = build_email_message(config, "Subject", "Body")

        self.assertEqual(message["From"], "alerts@example.com")
        self.assertEqual(message["To"], "one@example.com, two@example.com")
        self.assertEqual(message["Subject"], "Subject")
        self.assertEqual(message.get_content().strip(), "Body")


if __name__ == "__main__":
    unittest.main()
