from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo


LOCAL_TIMEZONE = ZoneInfo("Europe/Warsaw")


def format_event_date(value: datetime) -> str:
    return value.astimezone(LOCAL_TIMEZONE).strftime("%Y-%m-%d %H:%M %Z")


def format_alert_line(alert: dict) -> str:
    location_parts = [
        value
        for value in (alert["venue_name"], alert["city"], alert["country_code"])
        if value
    ]
    location = ", ".join(location_parts) if location_parts else "unknown location"
    event_url = alert["event_url"] or "no event url"

    return (
        f"[#{alert['alert_id']}] {alert['artist_name']} | "
        f"{format_event_date(alert['event_date'])} | "
        f"{location} | match={alert['match_type']} | {event_url}"
    )


def format_alert_email_subject(alerts: list[dict]) -> str:
    if len(alerts) == 1:
        return "1 new concert alert"
    return f"{len(alerts)} new concert alerts"


def format_alert_email_body(alerts: list[dict]) -> str:
    lines = [
        "New concert alerts:",
        "",
        *(format_alert_line(alert) for alert in alerts),
        "",
        "Generated by The Live Music Project.",
    ]
    return "\n".join(lines)
